-- ----------------------------
-- 背景图片地址
-- ----------------------------
SET @instance_background_img = '/group1/default/20210513/17/59/6/云资源监控-背景.png';

-- ----------------------------
-- 版本
-- ----------------------------
SET @version = 1;


INSERT INTO `view_instance`(`business_id`, `instance_background_color`, `instance_background_img`,
                            `instance_width`, `instance_height`, `instance_title`, `instance_view_thumbnail`, `instance_version`,
                            `create_id`, `create_time`, `update_id`, `update_time`, `del_flag`)
VALUES (1, '#263546', @instance_background_img, 1920, 1080, '', '', @version, 1, '2021-05-26 13:30:26', 1, '2021-05-26 17:36:42', 1);


SET @instance_id = @@IDENTITY;


-- ----------------------------
-- \"database\":9
-- 更换为自己的ID
-- ----------------------------
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        35,
        'chart0',
        8000,
        '{\"title\":\" 大数据计算服务运维视屏——测试项目\",\"fontColor\":\"#ffffff\",\"fontSize\":28,\"height\":35,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        500,
        215,
        15,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart1',
        8000,
        '{\"title\":\"服务器整体监测\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        180,
        60,
        100,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart2',
        8000,
        '{\"title\":\"MaxCompute任务总数\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        250,
        60,
        305,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart3',
        8000,
        '{\"title\":\"任务情况\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        125,
        895,
        305,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart4',
        8000,
        '{\"title\":\"表平均容量\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        130,
        1545,
        305,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart5',
        8000,
        '{\"title\":\"表储存容量\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        135,
        60,
        715,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart6',
        8000,
        '{\"title\":\"运行耗时最长任务\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        200,
        495,
        715,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        50,
        'chart7',
        8000,
        '{\"title\":\"资源耗时最大任务\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        200,
        895,
        715,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        20,
        'chart8',
        8000,
        '{\"title\":\"计算资源消耗\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        115,
        75,
        160,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        20,
        'chart9',
        8000,
        '{\"title\":\"磁盘总空间/利用率\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        160,
        530,
        160,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        20,
        'chart10',
        8000,
        '{\"title\":\"内存总数/利用率\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        140,
        985,
        160,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        20,
        'chart11',
        8000,
        '{\"title\":\"在线结点数/结点率\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        155,
        1440,
        160,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"select sum(data) as data from template_1_crc_sum\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        50,
        'chart12',
        8000,
        '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"GB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        135,
        75,
        205,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_crc_line\",\"chartType\":\"LineNormal\"}',
        'LineNormal',
        'false',
        '[]',
        100,
        'chart13',
        8000,
        '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"30\",\"30\"],[\"02/01\",\"160\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"90\",\"120\"],[\"05/01\",\"20\",\"70\"],[\"06/01\",\"190\",\"100\"],[\"07/01\",\"100\",\"70\"],[\"08/01\",\"150\",\"90\"],[\"09/01\",\"90\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}',
        'false',
        225,
        230,
        160,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tds_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        50,
        'chart14',
        8000,
        '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"TB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        90,
        530,
        205,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart15',
        8000,
        '{\"title\":\"/\",\"fontColor\":\"#ffffff\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}',
        'false',
        30,
        600,
        218,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tds_sum WHERE type = \'ratio\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        35,
        'chart16',
        8000,
        '{\"fontColor\":\"#ffffff\",\"fontSize\":32,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        80,
        635,
        214,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tds_line\",\"chartType\":\"LineNormal\"}',
        'LineNormal',
        'false',
        '[]',
        100,
        'chart17',
        8000,
        '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"90\",\"30\"],[\"02/01\",\"30\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"20\",\"180\"],[\"05/01\",\"50\",\"70\"],[\"06/01\",\"190\",\"120\"],[\"07/01\",\"170\",\"70\"],[\"08/01\",\"150\",\"90\"],[\"09/01\",\"40\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}',
        'false',
        225,
        715,
        160,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tm_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        50,
        'chart18',
        8000,
        '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"TB\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        90,
        985,
        205,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart19',
        8000,
        '{\"title\":\"/\",\"fontColor\":\"#ffffff\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}',
        'false',
        30,
        1060,
        218,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tm_sum WHERE type = \'ratio\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        35,
        'chart20',
        8000,
        '{\"fontColor\":\"#ffffff\",\"fontSize\":32,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        80,
        1095,
        214,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tm_line\",\"chartType\":\"LineNormal\"}',
        'LineNormal',
        'false',
        '[]',
        100,
        'chart21',
        8000,
        '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"16\",\"30\"],[\"02/01\",\"18\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"40\",\"120\"],[\"05/01\",\"20\",\"70\"],[\"06/01\",\"200\",\"100\"],[\"07/01\",\"90\",\"70\"],[\"08/01\",\"20\",\"90\"],[\"09/01\",\"90\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}',
        'false',
        225,
        1165,
        160,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_onn_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        50,
        'chart22',
        8000,
        '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"个\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        100,
        1440,
        205,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart23',
        8000,
        '{\"title\":\"/\",\"fontColor\":\"#ffffff\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}',
        'false',
        30,
        1535,
        218,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_onn_sum WHERE type = \'ratio\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        35,
        'chart24',
        8000,
        '{\"fontColor\":\"#ffffff\",\"fontSize\":32,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        80,
        1570,
        214,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_onn_line\",\"chartType\":\"LineNormal\"}',
        'LineNormal',
        'false',
        '[]',
        100,
        'chart25',
        8000,
        '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"30\",\"30\"],[\"02/01\",\"160\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"90\",\"120\"],[\"05/01\",\"20\",\"70\"],[\"06/01\",\"190\",\"100\"],[\"07/01\",\"100\",\"70\"],[\"08/01\",\"150\",\"90\"],[\"09/01\",\"90\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}',
        'false',
        225,
        1635,
        160,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_mcj_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        30,
        'chart26',
        8000,
        '{\"fontColor\":\"#b3b3b3\",\"fontSize\":22,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        110,
        100,
        360,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart27',
        8000,
        '{\"title\":\"同比\",\"fontColor\":\"#b3b3b3\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        60,
        550,
        360,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_mcj_sum WHERE type = \'year_on_tear\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        25,
        'chart28',
        8000,
        '{\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        60,
        610,
        365,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}',
        'TitleText',
        'false',
        '[]',
        30,
        'chart29',
        8000,
        '{\"title\":\"同比\",\"fontColor\":\"#b3b3b3\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}',
        'false',
        60,
        680,
        360,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_mcj_sum WHERE type = \'chain_ratio\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        25,
        'chart30',
        8000,
        '{\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        60,
        740,
        365,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_mcj_line\",\"chartType\":\"LineNormal\"}',
        'LineNormal',
        'false',
        '[]',
        275,
        'chart31',
        8000,
        '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"5%\",\"top\":\"10\",\"right\":\"10\",\"bottom\":\"10\"},\"xAxis\":{\"show\":false,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":false,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":true},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"60\",\"70\"],[\"02/01\",\"50\",\"80\"],[\"03/01\",\"60\",\"80\"],[\"04/01\",\"60\",\"150\"],[\"05/01\",\"100\",\"90\"],[\"06/01\",\"70\",\"130\"],[\"07/01\",\"150\",\"50\"],[\"08/01\",\"70\",\"20\"],[\"09/01\",\"20\",\"90\"],[\"10/01\",\"55\",\"130\"],[\"11/01\",\"220\",\"40\"],[\"12/01\",\"100\",\"80\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}',
        'false',
        775,
        45,
        405,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select name,value from template_1_jt_pie\",\"chartType\":\"PieNormal\"}',
        'PieNormal',
        'false',
        '[]',
        250,
        'chart32',
        8000,
        '{\"title\":{\"text\":\"任务类型分布\",\"x\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"},\"show\":true,\"left\":\"center\",\"top\":\"bottom\"},\"legend\":{\"show\":false},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"40%\"],\"radius\":[\"50%\",\"70%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"TYPE_1\",\"32\"],[\"TYPE_2\",\"54\"],[\"TYPE_3\",\"45\"],[\"TYPE_4\",\"12\"],[\"TYPE_5\",\"40\"]]},\"color\":[\"#E99B9F\",\"#EE8287\",\"#BE69AC\",\"#9E5DB7\",\"#973CE4\"]}',
        'false',
        250,
        900,
        380,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select name,value from template_1_js_pie\",\"chartType\":\"PieNormal\"}',
        'PieNormal',
        'false',
        '[]',
        250,
        'chart33',
        8000,
        '{\"title\":{\"text\":\"成功任务比例\",\"x\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"},\"show\":true,\"left\":\"center\",\"top\":\"bottom\"},\"legend\":{\"show\":false},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"40%\"],\"radius\":[\"50%\",\"70%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"TYPE_1\",\"82\"],[\"TYPE_2\",\"18\"]]},\"color\":[\"#EE8287\",\"#9E5DB7\",\"#973CE4\"]}',
        'false',
        250,
        1210,
        380,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tac_sum WHERE type = \'sum1\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        50,
        'chart34',
        8000,
        '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"GB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        160,
        1550,
        360,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tac_sum WHERE type = \'sum2\'\",\"chartType\":\"Counter\"}',
        'Counter',
        'false',
        '[]',
        50,
        'chart35',
        8000,
        '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"GB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}',
        'false',
        120,
        1750,
        360,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tac_histogram\",\"chartType\":\"HistogramNormal\"}',
        'HistogramNormal',
        'false',
        '[]',
        250,
        'chart36',
        8000,
        '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"color\":{\"x\":0,\"y\":0,\"x2\":0,\"y2\":1,\"type\":\"linear\",\"global\":false,\"colorStops\":[{\"offset\":0,\"color\":\"#E38A99\"},{\"offset\":1,\"color\":\"#9E5DB7\"}]}},\"barWidth\":0}],\"dataset\":{\"source\":[[\"dimension\"],[\"2月\",\"235\"],[\"3月\",\"156\"],[\"4月\",\"123\"],[\"5月\",\"423\"],[\"6月\",\"456\"],[\"7月\",\"356\"],[\"8月\",\"456\"],[\"9月\",\"853\"],[\"10月\",\"456\"],[\"11月\",\"456\"],[\"12月\",\"456\"]]}}',
        'false',
        350,
        1530,
        425,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tsc_histogram\",\"chartType\":\"HistogramNormal\"}',
        'HistogramNormal',
        'false',
        '[]',
        280,
        'chart37',
        8000,
        '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10%\",\"top\":\"10\",\"right\":\"10\",\"bottom\":\"10\"},\"xAxis\":{\"show\":false,\"type\":\"value\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":true,\"type\":\"category\"},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"color\":{\"x\":1,\"y\":0,\"x2\":0,\"y2\":0,\"type\":\"linear\",\"global\":false,\"colorStops\":[{\"offset\":0,\"color\":\"#E38A99\"},{\"offset\":1,\"color\":\"#9E5DB7\"}]}},\"barWidth\":\"50%\"}],\"dataset\":{\"source\":[[\"dimension\"],[\"上海\",\"23\"],[\"深证\",\"13\"],[\"合肥\",\"2\"],[\"成都\",\"9\"],[\"安徽\",\"5\"],[\"北京\",\"10\"],[\"杭州\",\"14\"],[\"长沙\",\"24\"]]}}',
        'false',
        385,
        40,
        775,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"sql\":\"select area,pv,series1,attribute from template_1_rlt_list\",\"chartType\":\"CarouselList\"}',
        'CarouselList',
        'false',
        '[]',
        300,
        'chart38',
        8000,
        '{\"header\":{\"show\":false,\"height\":35,\"fontColor\":\"#ffffff\",\"fontSize\":13,\"data\":[{\"width\":\"100px\",\"label\":\"area\"},{\"width\":\"100px\",\"label\":\"pv\"},{\"width\":\"100px\",\"label\":\"series1\"},{\"width\":\"80px\",\"label\":\"attribute\"}]},\"body\":{\"height\":35,\"fontColor\":\"#e2e2e2\",\"fontSize\":14,\"speed\":3,\"rowNum\":8,\"data\":[[\"北京\",\"6715\",\"99.7%\",\"6696\"],[\"天津\",\"6715\",\"99.7%\",\"6696\"],[\"河北\",\"6715\",\"99.7%\",\"6696\"],[\"山西\",\"6715\",\"99.7%\",\"6696\"],[\"内蒙古\",\"6715\",\"99.7%\",\"6696\"],[\"辽宁\",\"6715\",\"99.7%\",\"6696\"],[\"大连\",\"6715\",\"99.7%\",\"6696\"],[\"吉林\",\"6715\",\"99.7%\",\"6696\"],[\"贵州\",\"6715\",\"99.7%\",\"6696\"],[\"黑龙江\",\"6715\",\"99.7%\",\"6696\"],[\"浙江\",\"6715\",\"99.7%\",\"6696\"],[\"江苏\",\"6715\",\"99.7%\",\"6696\"],[\"海南\",\"6715\",\"99.7%\",\"6696\"],[\"广东\",\"6715\",\"99.7%\",\"6696\"],[\"广西\",\"6715\",\"99.7%\",\"6696\"],[\"安徽\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"西藏\",\"6715\",\"99.7%\",\"6696\"],[\"宁夏\",\"6715\",\"99.7%\",\"6696\"],[\"湖南\",\"6715\",\"99.7%\",\"6696\"],[\"湖北\",\"6715\",\"99.7%\",\"6696\"],[\"山东\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"青海\",\"6715\",\"99.7%\",\"6696\"]]}}',
        'false',
        390,
        455,
        775,
        @version);
INSERT INTO `view_chart_item` (`instance_id`,
                               `item_chart_data`,
                               `item_chart_type`,
                               `item_choose`,
                               `item_data`,
                               `item_height`,
                               `item_i`,
                               `item_interval`,
                               `item_option`,
                               `item_refresh`,
                               `item_width`,
                               `item_x`,
                               `item_y`,
                               `item_version`)
VALUES (@instance_id,
        '{\"dataSourceType\":\"DataBase\",\"database\":9,\"sql\":\"select area,pv,series1,attribute from template_1_rlt_list\",\"chartType\":\"CarouselList\"}',
        'CarouselList',
        'false',
        '[]',
        300,
        'chart39',
        8000,
        '{\"header\":{\"show\":false,\"height\":35,\"fontColor\":\"#ffffff\",\"fontSize\":13,\"data\":[{\"width\":\"250px\",\"label\":\"area\"},{\"width\":\"250px\",\"label\":\"pv\"},{\"width\":\"250px\",\"label\":\"series1\"},{\"width\":\"200px\",\"label\":\"attribute\"}]},\"body\":{\"height\":30,\"fontColor\":\"#e2e2e2\",\"fontSize\":12,\"speed\":3,\"rowNum\":10,\"data\":[[\"北京\",\"6715\",\"99.7%\",\"6696\"],[\"天津\",\"6715\",\"99.7%\",\"6696\"],[\"河北\",\"6715\",\"99.7%\",\"6696\"],[\"山西\",\"6715\",\"99.7%\",\"6696\"],[\"内蒙古\",\"6715\",\"99.7%\",\"6696\"],[\"辽宁\",\"6715\",\"99.7%\",\"6696\"],[\"大连\",\"6715\",\"99.7%\",\"6696\"],[\"吉林\",\"6715\",\"99.7%\",\"6696\"],[\"贵州\",\"6715\",\"99.7%\",\"6696\"],[\"黑龙江\",\"6715\",\"99.7%\",\"6696\"],[\"浙江\",\"6715\",\"99.7%\",\"6696\"],[\"江苏\",\"6715\",\"99.7%\",\"6696\"],[\"海南\",\"6715\",\"99.7%\",\"6696\"],[\"广东\",\"6715\",\"99.7%\",\"6696\"],[\"广西\",\"6715\",\"99.7%\",\"6696\"],[\"安徽\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"西藏\",\"6715\",\"99.7%\",\"6696\"],[\"宁夏\",\"6715\",\"99.7%\",\"6696\"],[\"湖南\",\"6715\",\"99.7%\",\"6696\"],[\"湖北\",\"6715\",\"99.7%\",\"6696\"],[\"山东\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"青海\",\"6715\",\"99.7%\",\"6696\"]]}}',
        'false',
        980,
        880,
        760,
        @version);