// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"data-view/database"
	"data-view/handler"
	"data-view/model"
)

// Injectors from wire.go:

// BuildInjector 生成注入器
func BuildInjector() (*Injector, func(), error) {
	engine, cleanup, err := database.InitXormDB()
	if err != nil {
		return nil, nil, err
	}
	dataSourceModel := &model.DataSourceModel{
		Engine: engine,
	}
	dataSourceHandler := &handler.DataSourceHandler{
		DataSourceModel: dataSourceModel,
	}
	imageModel := &model.ImageModel{
		Engine: engine,
	}
	imageHandler := &handler.ImageHandler{
		ImageModel: imageModel,
	}
	dataViewModel := &model.DataViewModel{
		Engine: engine,
	}
	dataViewHandler := &handler.DataViewHandler{
		DataViewModel:   dataViewModel,
		DataSourceModel: dataSourceModel,
	}
	router := &Router{
		DataSource: dataSourceHandler,
		Image:      imageHandler,
		DataView:   dataViewHandler,
	}
	injector := &Injector{
		Router: router,
	}
	return injector, func() {
		cleanup()
	}, nil
}
