/*
 Navicat Premium Data Transfer

 Source Server         : 本地服务器
 Source Server Type    : MySQL
 Source Server Version : 50732
 Source Host           : localhost:3306
 Source Schema         : data-view

 Target Server Type    : MySQL
 Target Server Version : 50732
 File Encoding         : 65001

 Date: 31/05/2021 20:43:24
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for data_source
-- ----------------------------
DROP TABLE IF EXISTS `data_source`;
CREATE TABLE `data_source`  (
  `data_source_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `business_id` bigint(20) NULL DEFAULT NULL COMMENT '企业ID',
  `data_source_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源名称',
  `data_source_type` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源类型',
  `data_source_database_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源的数据库名称',
  `data_source_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源的IP地址',
  `data_source_port` int(5) NULL DEFAULT NULL COMMENT '数据源的端口号',
  `data_source_username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源的账户名称',
  `data_source_password` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源的账户密码',
  `create_id` bigint(20) NULL DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_id` bigint(20) NULL DEFAULT NULL COMMENT '更新者ID',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint(4) NULL DEFAULT NULL COMMENT '删除标识（-1：不存在；1：存在）',
  PRIMARY KEY (`data_source_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 14 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of data_source
-- ----------------------------
INSERT INTO `data_source` VALUES (9, 1, 'data-view-template', 'MySQL', 'data-view-template', '127.0.0.1', 3306, 'root', 'root', 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);

-- ----------------------------
-- Table structure for image
-- ----------------------------
DROP TABLE IF EXISTS `image`;
CREATE TABLE `image`  (
  `image_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `image_name` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '图片名称',
  `image_path` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '图片位置',
  `image_size` bigint(20) NULL DEFAULT NULL COMMENT '图片大小',
  `business_id` bigint(20) NULL DEFAULT NULL COMMENT '企业ID',
  `create_id` bigint(20) NULL DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_id` bigint(20) NULL DEFAULT NULL COMMENT '更新者ID',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint(4) NULL DEFAULT NULL COMMENT '删除标识（-1：不存在；1：存在）',
  PRIMARY KEY (`image_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 22 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of image
-- ----------------------------
INSERT INTO `image` VALUES (9, '云资源监控-背景.png', '/group1/default/20210513/17/59/6/云资源监控-背景.png', 61983, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);
INSERT INTO `image` VALUES (10, '企业实时销售数据-背景.png', '/group1/default/20210513/18/00/6/企业实时销售数据-背景.png', 758743, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);
INSERT INTO `image` VALUES (11, '通用模板1-背景.png', '/group1/default/20210513/18/01/6/通用模板1-背景.png', 27247, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);
INSERT INTO `image` VALUES (12, '云服务监控-背景.png', '/group1/default/20210513/18/03/6/云服务监控-背景.png', 44365, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);
INSERT INTO `image` VALUES (13, '零售行业数据可视化-背景.png', '/group1/default/20210513/18/01/6/零售行业数据可视化-背景.png', 545340, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);
INSERT INTO `image` VALUES (17, '云服务监控-背景-custom.png', '/storage/2021/0530/云服务监控-背景.png', 44365, 1, 1, '2021-05-30 15:58:43', 1, '2021-05-30 15:58:43', 1);
INSERT INTO `image` VALUES (18, '云资源监控-背景-custom.png', '/storage/2021/0530/云资源监控-背景.png', 61983, 1, 1, '2021-05-30 21:27:37', 1, '2021-05-30 21:27:37', 1);
INSERT INTO `image` VALUES (19, '企业实时销售数据-背景-custom.png', '/storage/2021/0530/企业实时销售数据-背景.png', 758743, 1, 1, '2021-05-30 21:28:07', 1, '2021-05-30 21:28:07', 1);
INSERT INTO `image` VALUES (20, '通用模板1-背景-custom.png', '/storage/2021/0531/通用模板1-背景.png', 27247, 1, 1, '2021-05-31 13:40:13', 1, '2021-05-31 13:40:13', 1);
INSERT INTO `image` VALUES (21, '零售行业数据可视化-背景-custom.png', '/storage/2021/0531/零售行业数据可视化-背景.png', 545340, 1, 1, '2021-05-31 19:40:28', 1, '2021-05-31 19:40:28', 1);

-- ----------------------------
-- Table structure for view_chart_item
-- ----------------------------
DROP TABLE IF EXISTS `view_chart_item`;
CREATE TABLE `view_chart_item`  (
  `item_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `instance_id` bigint(20) NULL DEFAULT NULL,
  `item_chart_data` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `item_chart_type` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item_lock` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item_choose` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item_data` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `item_height` bigint(20) NULL DEFAULT NULL,
  `item_i` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item_interval` bigint(20) NULL DEFAULT NULL,
  `item_option` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `item_refresh` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item_width` bigint(20) NULL DEFAULT NULL,
  `item_x` bigint(20) NULL DEFAULT NULL,
  `item_y` bigint(20) NULL DEFAULT NULL,
  `item_version` bigint(20) NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2445 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of view_chart_item
-- ----------------------------
INSERT INTO `view_chart_item` VALUES (2306, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 50, 'chart0', 8000, '{\"title\":\"云计算服务监控\",\"fontColor\":\"#ffffff\",\"fontSize\":40,\"height\":50,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}', 'false', 400, 755, 40, 1);
INSERT INTO `view_chart_item` VALUES (2307, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart1', 8000, '{\"title\":\"任务总量\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 100, 120, 1);
INSERT INTO `view_chart_item` VALUES (2308, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select x,y,legend from template_3_tta_line\",\"chartType\":\"LineArea\"}', 'LineArea', 'false', 'false', '[]', 225, 'chart2', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线面积图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"10%\",\"top\":\"5%\",\"right\":\"5%\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"boundaryGap\":false},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"show\":true},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"areaStyle\":{\"color\":\"rgba(0, 200, 220, 0.1)\"},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{},\"areaStyle\":{\"color\":\"rgba(0, 110, 255, 0.1)\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"s1\",\"s2\"],[\"01/01\",\"1160\",\"600\"],[\"02/01\",\"600\",\"800\"],[\"03/01\",\"1800\",\"120\"],[\"04/01\",\"400\",\"1200\"],[\"05/01\",\"1300\",\"200\"],[\"06/01\",\"600\",\"500\"]]},\"color\":[\"#00C8DC\",\"#006EFF\"]}', 'false', 415, 80, 190, 1);
INSERT INTO `view_chart_item` VALUES (2309, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart3', 8000, '{\"title\":\"云计算趋势\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 120, 590, 120, 1);
INSERT INTO `view_chart_item` VALUES (2310, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_3_cctt_bar UNION select * from template_3_cctt_line\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', 'false', '[]', 250, 'chart4', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"10\",\"top\":\"5%\",\"right\":\"10\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"show\":false},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[0,0,0,0]},\"barWidth\":\"35%\"},{\"type\":\"line\",\"itemStyle\":{\"borderRadius\":[0,0,0,0]}}],\"dataset\":{\"source\":[[\"dimension\",\"bar\",\"line\"],[\"01/01\",\"40\",\"60\"],[\"02/01\",\"20\",\"100\"],[\"03/01\",\"70\",\"90\"],[\"04/01\",\"100\",\"140\"],[\"05/01\",\"40\",\"80\"],[\"06/01\",\"20\",\"50\"],[\"07/01\",\"30\",\"100\"],[\"08/01\",\"45\",\"90\"],[\"09/01\",\"120\",\"150\"],[\"10/01\",\"60\",\"80\"],[\"11/01\",\"50\",\"90\"],[\"12/01\",\"15\",\"50\"]]},\"color\":[\"#006EFF\",\"#6E3CFF\"]}', 'false', 795, 570, 170, 1);
INSERT INTO `view_chart_item` VALUES (2311, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart5', 8000, '{\"title\":\"云计算总资源\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 150, 1450, 120, 1);
INSERT INTO `view_chart_item` VALUES (2312, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_3_tccr_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'false', 'false', '[]', 225, 'chart6', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"10%\",\"top\":\"5%\",\"right\":\"\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"series\":[{\"type\":\"line\",\"lineStyle\":{}},{\"type\":\"line\",\"lineStyle\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"s1\",\"s2\"],[\"01/01\",\"1160\",\"600\"],[\"02/01\",\"600\",\"800\"],[\"03/01\",\"1800\",\"120\"],[\"04/01\",\"400\",\"1200\"],[\"05/01\",\"1300\",\"200\"],[\"06/01\",\"600\",\"500\"]]},\"color\":[\"#00C8DC\",\"#006EFF\"]}', 'false', 400, 1430, 190, 1);
INSERT INTO `view_chart_item` VALUES (2313, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart7', 8000, '{\"title\":\"任务分布\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 100, 450, 1);
INSERT INTO `view_chart_item` VALUES (2314, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"max\":\"max\",\"dimension\":\"legend\",\"sql\":\"select * from template_3_td_radar\",\"chartType\":\"RadarNormal\"}', 'RadarNormal', 'false', 'false', '[]', 200, 'chart8', 8000, '{\"title\":{\"show\":false,\"text\":\"标准雷达图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"radar\":{\"indicator\":[{\"max\":\"200\",\"name\":\"A\"},{\"max\":\"200\",\"name\":\"B\"},{\"max\":\"200\",\"name\":\"C\"},{\"max\":\"200\",\"name\":\"D\"},{\"max\":\"200\",\"name\":\"E\"},{\"max\":\"200\",\"name\":\"F\"}],\"center\":[\"50%\",\"50%\"],\"radius\":[0,\"70\"],\"axisLine\":{},\"axisLabel\":{},\"axisTick\":{},\"splitLine\":{},\"splitArea\":{\"show\":false},\"splitNumber\":3},\"series\":[{\"type\":\"radar\",\"itemStyle\":{},\"lineStyle\":{},\"data\":[{\"name\":\"s1\",\"value\":[\"80\",\"50\",\"100\",\"60\",\"40\",\"50\"]},{\"name\":\"s2\",\"value\":[\"150\",\"180\",\"170\",\"120\",\"140\",\"110\"]}],\"symbol\":\"none\"}],\"color\":[\"#FF5A32\",\"#006EFF\"]}', 'false', 180, 80, 510, 1);
INSERT INTO `view_chart_item` VALUES (2315, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart9', 8000, '{\"title\":\"任务成功\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 325, 450, 1);
INSERT INTO `view_chart_item` VALUES (2316, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select * from template_3_ts_pie_new\",\"chartType\":\"PieNormal\"}', 'PieNormal', 'false', 'false', '[]', 200, 'chart10', 8000, '{\"title\":{\"text\":\"62%\",\"x\":\"center\",\"textStyle\":{\"color\":\"#98a0c4\"},\"show\":true,\"left\":\"center\",\"top\":\"center\"},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"50%\"],\"radius\":[\"70%\",\"85%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"成功\",\"62\"],[\"未成功\",\"38\"]]},\"color\":[\"#7760F6\",\"#2C345C\"]}', 'false', 180, 310, 510, 1);
INSERT INTO `view_chart_item` VALUES (2317, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart11', 8000, '{\"title\":\"任务管理\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 590, 450, 1);
INSERT INTO `view_chart_item` VALUES (2318, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"sql\":\"select * from template_3_tm_list\",\"chartType\":\"CarouselList\"}', 'CarouselList', 'false', 'false', '[]', 530, 'chart12', 8000, '{\"header\":{\"show\":true,\"height\":40,\"fontColor\":\"#ffffff\",\"fontSize\":15,\"data\":[{\"width\":\"150px\",\"label\":\"时间\"},{\"width\":\"120px\",\"label\":\"任务1\"},{\"width\":\"120px\",\"label\":\"任务2\"}]},\"body\":{\"height\":40,\"fontColor\":\"#E2E2E2\",\"fontSize\":15,\"speed\":3,\"rowNum\":12,\"data\":[[\"2016-09\",\"100.2\",\"101.6\"],[\"2016-10\",\"101.7\",\"103.3\"],[\"2016-11\",\"104.5\",\"104.6\"],[\"2016-12\",\"106.8\",\"103.5\"],[\"2017-01\",\"108.5\",\"104.5\"],[\"2017-02\",\"109.3\",\"100.1\"],[\"2017-03\",\"108.4\",\"97.7\"],[\"2017-04\",\"106.8\",\"97.2\"],[\"2017-05\",\"106.2\",\"97\"],[\"2017-06\",\"106.1\",\"98.2\"],[\"2017-07\",\"105.8\",\"98.7\"],[\"2017-08\",\"106.7\",\"99.8\"],[\"2017-09\",\"100\",\"120\"]]}}', 'false', 400, 550, 500, 1);
INSERT INTO `view_chart_item` VALUES (2319, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart13', 8000, '{\"title\":\"平均容量\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 1015, 450, 1);
INSERT INTO `view_chart_item` VALUES (2320, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_3_ac_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', 'false', '[]', 225, 'chart14', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"10%\",\"top\":\"5%\",\"right\":\"\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"show\":true},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[0,0,0,0]}},{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[0,0,0,0]}}],\"dataset\":{\"source\":[[\"dimension\",\"data1\",\"data2\"],[\"02/02\",\"80\",\"50\"],[\"02/03\",\"50\",\"150\"],[\"02/04\",\"160\",\"120\"],[\"02/05\",\"120\",\"190\"],[\"02/06\",\"40\",\"140\"]]},\"color\":[\"#006EFF\",\"#00C8DC\"]}', 'false', 365, 1000, 500, 1);
INSERT INTO `view_chart_item` VALUES (2321, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart15', 8000, '{\"title\":\"CPU利用率\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 120, 1450, 450, 1);
INSERT INTO `view_chart_item` VALUES (2322, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select * from template_3_cpuur_pie_new\",\"chartType\":\"PieNormal\"}', 'PieNormal', 'false', 'false', '[]', 240, 'chart16', 8000, '{\"title\":{\"text\":\"60%\",\"x\":\"center\",\"textStyle\":{\"color\":\"#98a0c4\"},\"show\":true,\"left\":\"center\",\"top\":\"center\"},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"50%\"],\"radius\":[\"60%\",\"75%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"利用\",\"60\"],[\"未利用\",\"40\"]]},\"color\":[\"#00C8DC\",\"#2C345C\"]}', 'false', 400, 1430, 500, 1);
INSERT INTO `view_chart_item` VALUES (2323, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart17', 8000, '{\"title\":\"任务完成率\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 120, 100, 750, 1);
INSERT INTO `view_chart_item` VALUES (2324, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select x,y,legend from template_3_tcr_line\",\"chartType\":\"LineArea\"}', 'LineArea', 'false', 'false', '[]', 200, 'chart18', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线面积图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"10%\",\"top\":\"5%\",\"right\":\"5%\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"boundaryGap\":false},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"show\":true},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"areaStyle\":{\"color\":\"rgba(0, 110, 255, 0.7)\"},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{},\"areaStyle\":{\"color\":\"rgba(0, 200, 220, 0.7)\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"s1\",\"s2\"],[\"A\",\"1200\",\"150\"],[\"B\",\"1100\",\"300\"],[\"C\",\"1700\",\"700\"],[\"D\",\"900\",\"400\"],[\"E\",\"1200\",\"500\"],[\"F\",\"800\",\"300\"],[\"G\",\"700\",\"300\"]]},\"color\":[]}', 'false', 400, 80, 825, 1);
INSERT INTO `view_chart_item` VALUES (2325, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart19', 8000, '{\"title\":\"存储容量\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 1015, 750, 1);
INSERT INTO `view_chart_item` VALUES (2326, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_3_sc_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', 'false', '[]', 240, 'chart20', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"5%\",\"top\":\"5%\",\"right\":\"\",\"bottom\":\"5%\"},\"xAxis\":{\"show\":false,\"type\":\"value\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"type\":\"category\",\"show\":true},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[0,0,0,0]},\"barWidth\":\"40%\"}],\"dataset\":{\"source\":[[\"dimension\"],[\"A\",\"80\"],[\"B\",\"50\"],[\"C\",\"160\"],[\"D\",\"120\"],[\"E\",\"40\"]]},\"color\":[\"#006EFF\"]}', 'false', 400, 1000, 800, 1);
INSERT INTO `view_chart_item` VALUES (2327, 87, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart21', 8000, '{\"title\":\"内存利用率\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 120, 1450, 750, 1);
INSERT INTO `view_chart_item` VALUES (2328, 87, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select x,y,legend from template_3_mu_line\",\"chartType\":\"LineArea\"}', 'LineArea', 'false', 'false', '[]', 230, 'chart22', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线面积图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"10%\",\"top\":\"5%\",\"right\":\"5%\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"boundaryGap\":false},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"show\":true},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"areaStyle\":{\"color\":\"rgba(0, 110, 255, 0.14)\"}}],\"dataset\":{\"source\":[[\"dimension\"],[\"A\",\"1100\"],[\"B\",\"600\"],[\"C\",\"1800\"],[\"D\",\"400\"],[\"E\",\"1300\"],[\"F\",\"600\"]]},\"color\":[\"#006EFF\"]}', 'false', 400, 1435, 805, 1);
INSERT INTO `view_chart_item` VALUES (2329, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 45, 'chart0', 8000, '{\"title\":\"企业实时销售数据\",\"fontColor\":\"#ffffff\",\"fontSize\":35,\"height\":45,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 300, 50, 30, 1);
INSERT INTO `view_chart_item` VALUES (2330, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 35, 'chart1', 8000, '{\"title\":\"销售总额\",\"fontColor\":\"#73aae5\",\"fontSize\":30,\"height\":35,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 130, 755, 180, 1);
INSERT INTO `view_chart_item` VALUES (2331, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart2', 8000, '{\"title\":\"同比增长\",\"fontColor\":\"#73aae5\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 95, 250, 1);
INSERT INTO `view_chart_item` VALUES (2332, 86, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select * from template_2_map\",\"chartType\":\"MapChina\"}', 'MapChina', 'false', 'false', '[]', 700, 'chart3', 8000, '{\"title\":{\"show\":false,\"text\":\"中国地图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"visualMap\":{\"show\":true,\"text\":[],\"type\":\"continuous\",\"calculable\":true,\"left\":\"left\",\"top\":\"bottom\",\"min\":5000,\"max\":10000,\"color\":[\"#711D8E\",\"#484CDC\",\"#24CBFF\"]},\"geo\":{\"map\":\"china\"},\"series\":[{\"type\":\"map\",\"map\":\"china\",\"itemStyle\":{\"areaColor\":\"#080B19\",\"borderColor\":\"#00C8DC\"},\"showLegendSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"北京\",\"7040\"],[\"天津\",\"9876\"],[\"上海\",\"8278\"],[\"重庆\",\"8906\"],[\"河北\",\"9716\"],[\"河南\",\"5617\"],[\"云南\",\"7151\"],[\"辽宁\",\"6743\"],[\"黑龙江\",\"7202\"],[\"湖南\",\"9389\"],[\"安徽\",\"9485\"],[\"山东\",\"6896\"],[\"新疆\",\"7260\"],[\"江苏\",\"9821\"],[\"浙江\",\"7515\"],[\"江西\",\"5478\"],[\"湖北\",\"9371\"],[\"广西\",\"9802\"],[\"甘肃\",\"7963\"],[\"山西\",\"7768\"],[\"内蒙古\",\"6326\"],[\"陕西\",\"8913\"],[\"吉林\",\"8976\"],[\"福建\",\"6401\"],[\"贵州\",\"7137\"],[\"广东\",\"7612\"],[\"青海\",\"7889\"],[\"西藏\",\"8218\"],[\"四川\",\"5466\"],[\"宁夏\",\"7034\"],[\"海南\",\"5392\"],[\"台湾\",\"6428\"],[\"香港\",\"6802\"],[\"澳门\",\"6657\"]]}}', 'false', 920, 75, 305, 1);
INSERT INTO `view_chart_item` VALUES (2333, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 25, 'chart4', 8000, '{\"title\":\"一季度销售进度\",\"fontColor\":\"#73aae5\",\"fontSize\":20,\"height\":25,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}', 'false', 150, 1045, 35, 1);
INSERT INTO `view_chart_item` VALUES (2334, 86, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select * from template_2_sp_pie_new\",\"chartType\":\"PieNormal\"}', 'PieNormal', 'false', 'false', '[]', 205, 'chart5', 8000, '{\"title\":{\"text\":\"85%\",\"x\":\"center\",\"textStyle\":{\"color\":\"#98a0c4\"},\"show\":true,\"left\":\"center\",\"top\":\"center\"},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"50%\"],\"radius\":[\"60%\",\"75%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"完成\",\"85\"],[\"未完成\",\"15\"]]},\"color\":[\"#7760F6\",\"#2C345C\"]}', 'false', 410, 1040, 65, 1);
INSERT INTO `view_chart_item` VALUES (2335, 86, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"select data from template_2_sv_count\",\"chartType\":\"Counter\"}', 'Counter', 'false', 'false', '[]', 45, 'chart6', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":25,\"fontWeight\":\"normal\",\"textAlign\":\"center\",\"thousandth\":true,\"prefix\":{\"title\":\"一季度销售额\",\"fontColor\":\"#73aae5\",\"fontSize\":18,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"万\",\"fontColor\":\"#73aae5\",\"fontSize\":18,\"fontWeight\":\"normal\"}}', 'false', 180, 1150, 270, 1);
INSERT INTO `view_chart_item` VALUES (2336, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 25, 'chart7', 8000, '{\"title\":\"同比增长\",\"fontColor\":\"#73aae5\",\"fontSize\":18,\"height\":25,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 80, 1150, 315, 1);
INSERT INTO `view_chart_item` VALUES (2337, 86, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"select data from template_2_svg_count\",\"chartType\":\"Counter\"}', 'Counter', 'false', 'false', '[]', 30, 'chart8', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":25,\"fontWeight\":\"normal\",\"textAlign\":\"center\",\"thousandth\":true,\"prefix\":{\"title\":\"+\",\"fontColor\":\"#ff0000\",\"fontSize\":28,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":25,\"fontWeight\":\"normal\"}}', 'false', 110, 1235, 310, 1);
INSERT INTO `view_chart_item` VALUES (2338, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 25, 'chart9', 8000, '{\"title\":\"品类销售额占比\",\"fontColor\":\"#73aae5\",\"fontSize\":20,\"height\":25,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 150, 1470, 35, 1);
INSERT INTO `view_chart_item` VALUES (2339, 86, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select name,value from template_2_ss_pie\",\"chartType\":\"PieNormal\"}', 'PieNormal', 'false', 'false', '[]', 315, 'chart10', 8000, '{\"title\":{\"text\":\"普通饼图\",\"x\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"},\"show\":false},\"legend\":{\"show\":true,\"textStyle\":{\"color\":\"#ffffff\"},\"type\":\"plain\",\"orient\":\"horizontal\",\"top\":\"265\",\"left\":\"55\"},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"50%\"],\"radius\":[0,\"55%\"],\"roseType\":\"radius\",\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"数码类\",\"371570\"],[\"日用品\",\"296016\"],[\"快消类\",\"161953\"],[\"食品类\",\"125822\"]]},\"color\":[\"#24CBFF\",\"#7760F6\",\"#484CDC\",\"#711D8E\"]}', 'false', 410, 1465, 65, 1);
INSERT INTO `view_chart_item` VALUES (2340, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 25, 'chart11', 8000, '{\"title\":\"销售品牌排名\",\"fontColor\":\"#73aae5\",\"fontSize\":20,\"height\":25,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 150, 1045, 400, 1);
INSERT INTO `view_chart_item` VALUES (2341, 86, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_2_sbr_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', 'false', '[]', 285, 'chart12', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false},\"grid\":{\"left\":\"15%\",\"top\":\"10%\",\"right\":\"5%\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"value\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"type\":\"category\"},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[80,80,80,80]},\"barWidth\":\"40%\"}],\"dataset\":{\"source\":[[\"dimension\"],[\"三星\",\"641731\"],[\"vivo\",\"775032\"],[\"oppo\",\"802838\"],[\"华为\",\"954719\"],[\"小米\",\"1281971\"],[\"iPhone\",\"1570755\"]]},\"color\":[\"#24CBFF\"]}', 'false', 410, 1040, 430, 1);
INSERT INTO `view_chart_item` VALUES (2342, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 25, 'chart13', 8000, '{\"title\":\"城市销售额排名\",\"fontColor\":\"#73aae5\",\"fontSize\":20,\"height\":25,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 150, 1470, 400, 1);
INSERT INTO `view_chart_item` VALUES (2343, 86, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_2_sr_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', 'false', '[]', 235, 'chart14', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false},\"grid\":{\"left\":\"20%\",\"top\":\"10%\",\"right\":\"5%\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[80,80,80,80]},\"barWidth\":\"35%\"}],\"dataset\":{\"source\":[[\"dimension\"],[\"北京\",\"1339783\"],[\"上海\",\"1394842\"],[\"杭州\",\"786996\"],[\"深圳\",\"550908\"],[\"广州\",\"612633\"],[\"连云港\",\"668681\"]]},\"color\":[\"#24CBFF\"]}', 'false', 410, 1465, 430, 1);
INSERT INTO `view_chart_item` VALUES (2344, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 25, 'chart15', 8000, '{\"title\":\"品牌分布\",\"fontColor\":\"#73aae5\",\"fontSize\":20,\"height\":25,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 1045, 725, 1);
INSERT INTO `view_chart_item` VALUES (2345, 86, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_2_bd_histogram\",\"chartType\":\"PictorialBar\"}', 'PictorialBar', 'false', 'false', '[]', 275, 'chart16', 8000, '{\"title\":{\"text\":\"象形柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10%\",\"top\":\"10%\",\"right\":\"10%\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"pictorialBar\",\"itemStyle\":{\"opacity\":0.7},\"barCategoryGap\":\"-130%\",\"symbol\":\"path://M0,10 L10,10 C5.5,10 5.5,5 5,0 C4.5,5 4.5,10 0,10 z\"}],\"dataset\":{\"source\":[[\"dimension\"],[\"苹果\",\"9896\"],[\"三星\",\"8663\"],[\"华为\",\"7458\"],[\"oppo\",\"9102\"],[\"vivo\",\"5114\"],[\"小米\",\"8722\"]]},\"color\":[\"#24CBFF\"]}', 'false', 410, 1040, 755, 1);
INSERT INTO `view_chart_item` VALUES (2346, 86, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 25, 'chart17', 8000, '{\"title\":\"核心城市销售增长额\",\"fontColor\":\"#73aae5\",\"fontSize\":20,\"height\":25,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 200, 1470, 690, 1);
INSERT INTO `view_chart_item` VALUES (2347, 86, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_2_sg_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'false', 'false', '[]', 310, 'chart18', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"5%\",\"top\":\"5%\",\"right\":\"5%\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{}},{\"type\":\"line\",\"lineStyle\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"北京\",\"上海\"],[\"2014\",\"883192\",\"710627\"],[\"2015\",\"643885\",\"358548\"],[\"2016\",\"658223\",\"707107\"],[\"2017\",\"521328\",\"316168\"],[\"2018\",\"833451\",\"485196\"]]},\"color\":[\"#24CBFF\",\"#7760F6\"]}', 'false', 405, 1470, 725, 1);
INSERT INTO `view_chart_item` VALUES (2348, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 35, 'chart0', 8000, '{\"title\":\" 大数据计算服务运维视屏——测试项目\",\"fontColor\":\"#ffffff\",\"fontSize\":28,\"height\":35,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 500, 215, 15, 1);
INSERT INTO `view_chart_item` VALUES (2349, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart1', 8000, '{\"title\":\"服务器整体监测\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 180, 60, 100, 1);
INSERT INTO `view_chart_item` VALUES (2350, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart2', 8000, '{\"title\":\"MaxCompute任务总数\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 250, 60, 305, 1);
INSERT INTO `view_chart_item` VALUES (2351, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart3', 8000, '{\"title\":\"任务情况\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 125, 895, 305, 1);
INSERT INTO `view_chart_item` VALUES (2352, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart4', 8000, '{\"title\":\"表平均容量\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 130, 1545, 305, 1);
INSERT INTO `view_chart_item` VALUES (2353, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart5', 8000, '{\"title\":\"表储存容量\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 135, 60, 715, 1);
INSERT INTO `view_chart_item` VALUES (2354, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart6', 8000, '{\"title\":\"运行耗时最长任务\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 200, 495, 715, 1);
INSERT INTO `view_chart_item` VALUES (2355, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 50, 'chart7', 8000, '{\"title\":\"资源耗时最大任务\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 200, 895, 715, 1);
INSERT INTO `view_chart_item` VALUES (2356, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 20, 'chart8', 8000, '{\"title\":\"计算资源消耗\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 115, 75, 160, 1);
INSERT INTO `view_chart_item` VALUES (2357, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 20, 'chart9', 8000, '{\"title\":\"磁盘总空间/利用率\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 160, 530, 160, 1);
INSERT INTO `view_chart_item` VALUES (2358, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 20, 'chart10', 8000, '{\"title\":\"内存总数/利用率\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 140, 985, 160, 1);
INSERT INTO `view_chart_item` VALUES (2359, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 20, 'chart11', 8000, '{\"title\":\"在线结点数/结点率\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 155, 1440, 160, 1);
INSERT INTO `view_chart_item` VALUES (2360, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"select sum(data) as data from template_1_crc_sum\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 50, 'chart12', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"GB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 135, 75, 205, 1);
INSERT INTO `view_chart_item` VALUES (2361, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_crc_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'true', 'false', '[]', 100, 'chart13', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"30\",\"30\"],[\"02/01\",\"160\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"90\",\"120\"],[\"05/01\",\"20\",\"70\"],[\"06/01\",\"190\",\"100\"],[\"07/01\",\"100\",\"70\"],[\"08/01\",\"150\",\"90\"],[\"09/01\",\"90\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 225, 230, 160, 1);
INSERT INTO `view_chart_item` VALUES (2362, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tds_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 50, 'chart14', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"TB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 90, 530, 205, 1);
INSERT INTO `view_chart_item` VALUES (2363, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart15', 8000, '{\"title\":\"/\",\"fontColor\":\"#ffffff\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}', 'false', 30, 600, 218, 1);
INSERT INTO `view_chart_item` VALUES (2364, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tds_sum WHERE type = \'ratio\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 35, 'chart16', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":32,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 80, 635, 214, 1);
INSERT INTO `view_chart_item` VALUES (2365, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tds_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'true', 'false', '[]', 100, 'chart17', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"90\",\"30\"],[\"02/01\",\"30\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"20\",\"180\"],[\"05/01\",\"50\",\"70\"],[\"06/01\",\"190\",\"120\"],[\"07/01\",\"170\",\"70\"],[\"08/01\",\"150\",\"90\"],[\"09/01\",\"40\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 225, 715, 160, 1);
INSERT INTO `view_chart_item` VALUES (2366, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tm_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 50, 'chart18', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"TB\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 90, 985, 205, 1);
INSERT INTO `view_chart_item` VALUES (2367, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart19', 8000, '{\"title\":\"/\",\"fontColor\":\"#ffffff\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}', 'false', 30, 1060, 218, 1);
INSERT INTO `view_chart_item` VALUES (2368, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tm_sum WHERE type = \'ratio\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 35, 'chart20', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":32,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 80, 1095, 214, 1);
INSERT INTO `view_chart_item` VALUES (2369, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tm_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'true', 'false', '[]', 100, 'chart21', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"16\",\"30\"],[\"02/01\",\"18\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"40\",\"120\"],[\"05/01\",\"20\",\"70\"],[\"06/01\",\"200\",\"100\"],[\"07/01\",\"90\",\"70\"],[\"08/01\",\"20\",\"90\"],[\"09/01\",\"90\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 225, 1165, 160, 1);
INSERT INTO `view_chart_item` VALUES (2370, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_onn_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 50, 'chart22', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"个\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 100, 1440, 205, 1);
INSERT INTO `view_chart_item` VALUES (2371, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart23', 8000, '{\"title\":\"/\",\"fontColor\":\"#ffffff\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}', 'false', 30, 1535, 218, 1);
INSERT INTO `view_chart_item` VALUES (2372, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_onn_sum WHERE type = \'ratio\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 35, 'chart24', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":32,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 80, 1570, 214, 1);
INSERT INTO `view_chart_item` VALUES (2373, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_onn_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'true', 'false', '[]', 100, 'chart25', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"30\",\"30\"],[\"02/01\",\"160\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"90\",\"120\"],[\"05/01\",\"20\",\"70\"],[\"06/01\",\"190\",\"100\"],[\"07/01\",\"100\",\"70\"],[\"08/01\",\"150\",\"90\"],[\"09/01\",\"90\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 225, 1635, 160, 1);
INSERT INTO `view_chart_item` VALUES (2374, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_mcj_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 30, 'chart26', 8000, '{\"fontColor\":\"#b3b3b3\",\"fontSize\":22,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 110, 100, 360, 1);
INSERT INTO `view_chart_item` VALUES (2375, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart27', 8000, '{\"title\":\"同比\",\"fontColor\":\"#b3b3b3\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 60, 550, 360, 1);
INSERT INTO `view_chart_item` VALUES (2376, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_mcj_sum WHERE type = \'year_on_tear\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 25, 'chart28', 8000, '{\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 60, 610, 365, 1);
INSERT INTO `view_chart_item` VALUES (2377, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'true', 'false', '[]', 30, 'chart29', 8000, '{\"title\":\"同比\",\"fontColor\":\"#b3b3b3\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 60, 680, 360, 1);
INSERT INTO `view_chart_item` VALUES (2378, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_mcj_sum WHERE type = \'chain_ratio\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 25, 'chart30', 8000, '{\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 60, 740, 365, 1);
INSERT INTO `view_chart_item` VALUES (2379, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_mcj_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'true', 'false', '[]', 275, 'chart31', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"5%\",\"top\":\"10\",\"right\":\"10\",\"bottom\":\"10\"},\"xAxis\":{\"show\":false,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":false,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":true},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"60\",\"70\"],[\"02/01\",\"50\",\"80\"],[\"03/01\",\"60\",\"80\"],[\"04/01\",\"60\",\"150\"],[\"05/01\",\"100\",\"90\"],[\"06/01\",\"70\",\"130\"],[\"07/01\",\"150\",\"50\"],[\"08/01\",\"70\",\"20\"],[\"09/01\",\"20\",\"90\"],[\"10/01\",\"55\",\"130\"],[\"11/01\",\"220\",\"40\"],[\"12/01\",\"100\",\"80\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 775, 45, 405, 1);
INSERT INTO `view_chart_item` VALUES (2380, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select name,value from template_1_jt_pie\",\"chartType\":\"PieNormal\"}', 'PieNormal', 'true', 'false', '[]', 250, 'chart32', 8000, '{\"title\":{\"text\":\"任务类型分布\",\"x\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"},\"show\":true,\"left\":\"center\",\"top\":\"bottom\"},\"legend\":{\"show\":false},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"40%\"],\"radius\":[\"50%\",\"70%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"TYPE_1\",\"32\"],[\"TYPE_2\",\"54\"],[\"TYPE_3\",\"45\"],[\"TYPE_4\",\"12\"],[\"TYPE_5\",\"40\"]]},\"color\":[\"#E99B9F\",\"#EE8287\",\"#BE69AC\",\"#9E5DB7\",\"#973CE4\"]}', 'false', 250, 900, 380, 1);
INSERT INTO `view_chart_item` VALUES (2381, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select name,value from template_1_js_pie\",\"chartType\":\"PieNormal\"}', 'PieNormal', 'true', 'false', '[]', 250, 'chart33', 8000, '{\"title\":{\"text\":\"成功任务比例\",\"x\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"},\"show\":true,\"left\":\"center\",\"top\":\"bottom\"},\"legend\":{\"show\":false},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"40%\"],\"radius\":[\"50%\",\"70%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"TYPE_1\",\"82\"],[\"TYPE_2\",\"18\"]]},\"color\":[\"#EE8287\",\"#9E5DB7\",\"#973CE4\"]}', 'false', 250, 1210, 380, 1);
INSERT INTO `view_chart_item` VALUES (2382, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tac_sum WHERE type = \'sum1\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 50, 'chart34', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"GB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 160, 1550, 360, 1);
INSERT INTO `view_chart_item` VALUES (2383, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tac_sum WHERE type = \'sum2\'\",\"chartType\":\"Counter\"}', 'Counter', 'true', 'false', '[]', 50, 'chart35', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"GB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 120, 1750, 360, 1);
INSERT INTO `view_chart_item` VALUES (2384, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tac_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'true', 'false', '[]', 250, 'chart36', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"color\":{\"x\":0,\"y\":0,\"x2\":0,\"y2\":1,\"type\":\"linear\",\"global\":false,\"colorStops\":[{\"offset\":0,\"color\":\"#E38A99\"},{\"offset\":1,\"color\":\"#9E5DB7\"}]}},\"barWidth\":0}],\"dataset\":{\"source\":[[\"dimension\"],[\"2月\",\"235\"],[\"3月\",\"156\"],[\"4月\",\"123\"],[\"5月\",\"423\"],[\"6月\",\"456\"],[\"7月\",\"356\"],[\"8月\",\"456\"],[\"9月\",\"853\"],[\"10月\",\"456\"],[\"11月\",\"456\"],[\"12月\",\"456\"]]}}', 'false', 350, 1530, 425, 1);
INSERT INTO `view_chart_item` VALUES (2385, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tsc_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'true', 'false', '[]', 280, 'chart37', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10%\",\"top\":\"10\",\"right\":\"10\",\"bottom\":\"10\"},\"xAxis\":{\"show\":false,\"type\":\"value\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":true,\"type\":\"category\"},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"color\":{\"x\":1,\"y\":0,\"x2\":0,\"y2\":0,\"type\":\"linear\",\"global\":false,\"colorStops\":[{\"offset\":0,\"color\":\"#E38A99\"},{\"offset\":1,\"color\":\"#9E5DB7\"}]}},\"barWidth\":\"50%\"}],\"dataset\":{\"source\":[[\"dimension\"],[\"上海\",\"23\"],[\"深证\",\"13\"],[\"合肥\",\"2\"],[\"成都\",\"9\"],[\"安徽\",\"5\"],[\"北京\",\"10\"],[\"杭州\",\"14\"],[\"长沙\",\"24\"]]}}', 'false', 385, 40, 775, 1);
INSERT INTO `view_chart_item` VALUES (2386, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"sql\":\"select area,pv,series1,attribute from template_1_rlt_list\",\"chartType\":\"CarouselList\"}', 'CarouselList', 'true', 'false', '[]', 300, 'chart38', 8000, '{\"header\":{\"show\":false,\"height\":35,\"fontColor\":\"#ffffff\",\"fontSize\":13,\"data\":[{\"width\":\"100px\",\"label\":\"area\"},{\"width\":\"100px\",\"label\":\"pv\"},{\"width\":\"100px\",\"label\":\"series1\"},{\"width\":\"80px\",\"label\":\"attribute\"}]},\"body\":{\"height\":35,\"fontColor\":\"#e2e2e2\",\"fontSize\":14,\"speed\":3,\"rowNum\":8,\"data\":[[\"北京\",\"6715\",\"99.7%\",\"6696\"],[\"天津\",\"6715\",\"99.7%\",\"6696\"],[\"河北\",\"6715\",\"99.7%\",\"6696\"],[\"山西\",\"6715\",\"99.7%\",\"6696\"],[\"内蒙古\",\"6715\",\"99.7%\",\"6696\"],[\"辽宁\",\"6715\",\"99.7%\",\"6696\"],[\"大连\",\"6715\",\"99.7%\",\"6696\"],[\"吉林\",\"6715\",\"99.7%\",\"6696\"],[\"贵州\",\"6715\",\"99.7%\",\"6696\"],[\"黑龙江\",\"6715\",\"99.7%\",\"6696\"],[\"浙江\",\"6715\",\"99.7%\",\"6696\"],[\"江苏\",\"6715\",\"99.7%\",\"6696\"],[\"海南\",\"6715\",\"99.7%\",\"6696\"],[\"广东\",\"6715\",\"99.7%\",\"6696\"],[\"广西\",\"6715\",\"99.7%\",\"6696\"],[\"安徽\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"西藏\",\"6715\",\"99.7%\",\"6696\"],[\"宁夏\",\"6715\",\"99.7%\",\"6696\"],[\"湖南\",\"6715\",\"99.7%\",\"6696\"],[\"湖北\",\"6715\",\"99.7%\",\"6696\"],[\"山东\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"青海\",\"6715\",\"99.7%\",\"6696\"]]}}', 'false', 390, 455, 775, 1);
INSERT INTO `view_chart_item` VALUES (2387, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"sql\":\"select area,pv,series1,attribute from template_1_rlt_list\",\"chartType\":\"CarouselList\"}', 'CarouselList', 'true', 'false', '[]', 300, 'chart39', 8000, '{\"header\":{\"show\":false,\"height\":35,\"fontColor\":\"#ffffff\",\"fontSize\":13,\"data\":[{\"width\":\"250px\",\"label\":\"area\"},{\"width\":\"250px\",\"label\":\"pv\"},{\"width\":\"250px\",\"label\":\"series1\"},{\"width\":\"200px\",\"label\":\"attribute\"}]},\"body\":{\"height\":30,\"fontColor\":\"#e2e2e2\",\"fontSize\":12,\"speed\":3,\"rowNum\":10,\"data\":[[\"北京\",\"6715\",\"99.7%\",\"6696\"],[\"天津\",\"6715\",\"99.7%\",\"6696\"],[\"河北\",\"6715\",\"99.7%\",\"6696\"],[\"山西\",\"6715\",\"99.7%\",\"6696\"],[\"内蒙古\",\"6715\",\"99.7%\",\"6696\"],[\"辽宁\",\"6715\",\"99.7%\",\"6696\"],[\"大连\",\"6715\",\"99.7%\",\"6696\"],[\"吉林\",\"6715\",\"99.7%\",\"6696\"],[\"贵州\",\"6715\",\"99.7%\",\"6696\"],[\"黑龙江\",\"6715\",\"99.7%\",\"6696\"],[\"浙江\",\"6715\",\"99.7%\",\"6696\"],[\"江苏\",\"6715\",\"99.7%\",\"6696\"],[\"海南\",\"6715\",\"99.7%\",\"6696\"],[\"广东\",\"6715\",\"99.7%\",\"6696\"],[\"广西\",\"6715\",\"99.7%\",\"6696\"],[\"安徽\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"西藏\",\"6715\",\"99.7%\",\"6696\"],[\"宁夏\",\"6715\",\"99.7%\",\"6696\"],[\"湖南\",\"6715\",\"99.7%\",\"6696\"],[\"湖北\",\"6715\",\"99.7%\",\"6696\"],[\"山东\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"青海\",\"6715\",\"99.7%\",\"6696\"]]}}', 'false', 980, 880, 760, 1);
INSERT INTO `view_chart_item` VALUES (2427, 88, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 50, 'chart0', 8000, '{\"title\":\"产品2019年度销售\",\"fontColor\":\"#ffffff\",\"fontSize\":34,\"height\":50,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}', 'false', 300, 810, 25, 1);
INSERT INTO `view_chart_item` VALUES (2428, 88, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart1', 8000, '{\"title\":\"数据标题\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 80, 120, 1);
INSERT INTO `view_chart_item` VALUES (2429, 88, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_4_data1_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', 'false', '[]', 200, 'chart2', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"10%\",\"top\":\"5%\",\"right\":\"\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[0,0,0,0]},\"barWidth\":\"40%\"}],\"dataset\":{\"source\":[[\"dimension\"],[\"一月\",\"90\"],[\"二月\",\"40\"],[\"三月\",\"180\"],[\"四月\",\"80\"],[\"五月\",\"120\"]]},\"color\":[\"#00C8DC\"]}', 'false', 316, 80, 190, 1);
INSERT INTO `view_chart_item` VALUES (2430, 88, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart3', 8000, '{\"title\":\"数据标题\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 80, 465, 1);
INSERT INTO `view_chart_item` VALUES (2431, 88, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_4_data2_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', 'false', '[]', 200, 'chart4', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"10%\",\"top\":\"5%\",\"right\":\"5%\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"value\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"type\":\"category\"},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[0,0,0,0]},\"barWidth\":\"40%\"}],\"dataset\":{\"source\":[[\"dimension\"],[\"一月\",\"80\"],[\"二月\",\"50\"],[\"三月\",\"160\"],[\"四月\",\"120\"]]},\"color\":[\"#5F5FFF\"]}', 'false', 315, 80, 530, 1);
INSERT INTO `view_chart_item` VALUES (2432, 88, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart5', 8000, '{\"title\":\"数据标题\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 80, 795, 1);
INSERT INTO `view_chart_item` VALUES (2433, 88, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select name,value from template_4_data3_pie\",\"chartType\":\"PieNormal\"}', 'PieNormal', 'false', 'false', '[]', 160, 'chart6', 8000, '{\"title\":{\"text\":\"普通饼图\",\"x\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"},\"show\":false},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"50%\"],\"radius\":[\"70%\",\"100%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"500元以下\",\"1800\"],[\"1K~2K元\",\"1200\"],[\"0.5K~1K元\",\"600\"]]},\"color\":[\"#006EFF\",\"#5F5FFF\",\"#00C8DC\"]}', 'false', 335, 70, 850, 1);
INSERT INTO `view_chart_item` VALUES (2434, 88, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"select data from template_4_data4_sum\",\"chartType\":\"Counter\"}', 'Counter', 'false', 'false', '[]', 50, 'chart7', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 250, 505, 140, 1);
INSERT INTO `view_chart_item` VALUES (2435, 88, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart8', 8000, '{\"title\":\"总销量\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 70, 505, 200, 1);
INSERT INTO `view_chart_item` VALUES (2436, 88, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select * from template_4_data4_map\",\"chartType\":\"MapChina\"}', 'MapChina', 'false', 'false', '[]', 680, 'chart9', 8000, '{\"title\":{\"show\":false,\"text\":\"中国地图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"visualMap\":{\"show\":false,\"text\":[],\"min\":50,\"max\":550,\"color\":[\"#00C8DC\",\"#080B19\"]},\"geo\":{\"map\":\"china\"},\"series\":[{\"type\":\"map\",\"map\":\"china\",\"itemStyle\":{\"areaColor\":\"#080B19\",\"borderColor\":\"#00C8DC\"},\"showLegendSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"四川\",\"100\"],[\"广东\",\"200\"],[\"香港\",\"300\"],[\"上海\",\"250\"],[\"青海\",\"50\"],[\"重庆\",\"350\"],[\"山东\",\"450\"],[\"辽宁\",\"550\"]]}}', 'false', 955, 480, 105, 1);
INSERT INTO `view_chart_item` VALUES (2437, 88, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart10', 8000, '{\"title\":\"数据标题\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 200, 505, 800, 1);
INSERT INTO `view_chart_item` VALUES (2438, 88, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select x,y,legend from template_4_data5_line\",\"chartType\":\"LineArea\"}', 'LineArea', 'false', 'false', '[]', 165, 'chart11', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线面积图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"5%\",\"top\":\"10%\",\"right\":\"5%\",\"bottom\":\"15%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"boundaryGap\":false},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"show\":true},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"areaStyle\":{\"color\":\"rgba(0,200,220,0.17)\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"data\"],[\"一月\",\"600\"],[\"二月\",\"80\"],[\"三月\",\"680\"],[\"四月\",\"1200\"],[\"五月\",\"600\"],[\"六月\",\"400\"],[\"七月\",\"800\"]]},\"color\":[\"#00C8DC\"]}', 'false', 895, 505, 840, 1);
INSERT INTO `view_chart_item` VALUES (2439, 88, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart12', 8000, '{\"title\":\"数据标题\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 1520, 120, 1);
INSERT INTO `view_chart_item` VALUES (2440, 88, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select x,y,legend from template_4_data6_line\",\"chartType\":\"LineArea\"}', 'LineArea', 'false', 'false', '[]', 205, 'chart13', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线面积图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"15%\",\"top\":\"5%\",\"right\":\"5%\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"boundaryGap\":false},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"show\":true},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"areaStyle\":{\"color\":\"rgba(109, 79, 250, 0.25)\"},\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{},\"areaStyle\":{\"color\":\"rgba(54, 227, 255, 0.15)\"},\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"data1\",\"data2\"],[\"一月\",\"100\",\"1100\"],[\"二月\",\"450\",\"800\"],[\"三月\",\"300\",\"1600\"],[\"四月\",\"1000\",\"600\"],[\"五月\",\"400\",\"1000\"],[\"六月\",\"800\",\"700\"]]},\"color\":[\"#6E3CFF\",\"#36E3FF\"]}', 'false', 320, 1520, 185, 1);
INSERT INTO `view_chart_item` VALUES (2441, 88, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart14', 8000, '{\"title\":\"数据标题\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 1515, 465, 1);
INSERT INTO `view_chart_item` VALUES (2442, 88, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_4_data7_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', 'false', '[]', 230, 'chart15', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"10%\",\"top\":\"5%\",\"right\":\"\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"show\":true},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[0,0,0,0]}},{\"type\":\"bar\",\"itemStyle\":{\"borderRadius\":[0,0,0,0]}}],\"dataset\":{\"source\":[[\"dimension\",\"data1\",\"data2\"],[\"一月\",\"80\",\"65\"],[\"二月\",\"50\",\"40\"],[\"三月\",\"160\",\"130\"],[\"四月\",\"120\",\"100\"],[\"五月\",\"40\",\"30\"]]},\"color\":[\"#6E3CFF\",\"#36E3FF\"]}', 'false', 325, 1515, 520, 1);
INSERT INTO `view_chart_item` VALUES (2443, 88, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', 'false', '[]', 30, 'chart16', 8000, '{\"title\":\"数据标题\",\"fontColor\":\"#ffffff\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 100, 1515, 795, 1);
INSERT INTO `view_chart_item` VALUES (2444, 88, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_4_data8_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'false', 'false', '[]', 160, 'chart17', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false,\"textStyle\":{\"color\":\"#ffffff\"}},\"grid\":{\"left\":\"15%\",\"top\":\"5%\",\"right\":\"\",\"bottom\":\"15%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"splitArea\":{},\"show\":true},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\"],[\"一月\",\"600\"],[\"二月\",\"80\"],[\"三月\",\"680\"],[\"四月\",\"1200\"],[\"五月\",\"600\"],[\"六月\",\"400\"]]},\"color\":[\"#5F5FFF\"]}', 'false', 320, 1515, 845, 1);

-- ----------------------------
-- Table structure for view_instance
-- ----------------------------
DROP TABLE IF EXISTS `view_instance`;
CREATE TABLE `view_instance`  (
  `instance_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '实例ID',
  `business_id` bigint(20) NULL DEFAULT NULL COMMENT '企业ID',
  `instance_background_color` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '背景颜色',
  `instance_background_img` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '背景图',
  `instance_width` bigint(20) NULL DEFAULT NULL COMMENT '宽',
  `instance_height` bigint(20) NULL DEFAULT NULL COMMENT '高',
  `instance_title` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '标题',
  `instance_view_thumbnail` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '缩略图',
  `instance_version` bigint(20) NULL DEFAULT NULL COMMENT '版本号',
  `create_id` bigint(20) NULL DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_id` bigint(20) NULL DEFAULT NULL COMMENT '更新者ID',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint(4) NULL DEFAULT NULL COMMENT '删除标识（-1：不存在；1：存在）',
  PRIMARY KEY (`instance_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 89 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of view_instance
-- ----------------------------
INSERT INTO `view_instance` VALUES (85, 1, '#263546', '/storage/2021/0530/云资源监控-背景.png', 1920, 1080, '云资源监控', '/storage/2021/0531/1622444749389_thumbnail.png', 1, 1, '2021-05-26 13:30:26', 1, '2021-05-31 15:05:49', 1);
INSERT INTO `view_instance` VALUES (86, 1, '#263546', '/storage/2021/0530/企业实时销售数据-背景.png', 1920, 1080, '企业实时销售数据', '/storage/2021/0531/1622444712949_thumbnail.png', 1, 1, '2021-05-29 15:17:35', 1, '2021-05-31 15:05:12', 1);
INSERT INTO `view_instance` VALUES (87, 1, '#263546', '/storage/2021/0530/云服务监控-背景.png', 1920, 1080, '云服务监控', '/storage/2021/0531/1622444588858_thumbnail.png', 1, 1, '2021-05-31 11:00:09', 1, '2021-05-31 15:03:08', 1);
INSERT INTO `view_instance` VALUES (88, 1, '#263546', '/storage/2021/0531/通用模板1-背景.png', 1920, 1080, '通用模板1', '/storage/2021/0531/1622452611974_thumbnail.png', 1, 1, '2021-05-31 17:02:04', 1, '2021-05-31 17:16:52', 1);

SET FOREIGN_KEY_CHECKS = 1;
