/*
 Navicat Premium Data Transfer

 Source Server         : 本地服务器
 Source Server Type    : MySQL
 Source Server Version : 50732
 Source Host           : localhost:3306
 Source Schema         : data-view

 Target Server Type    : MySQL
 Target Server Version : 50732
 File Encoding         : 65001

 Date: 28/05/2021 09:38:52
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for data_source
-- ----------------------------
DROP TABLE IF EXISTS `data_source`;
CREATE TABLE `data_source`  (
  `data_source_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `business_id` bigint(20) NULL DEFAULT NULL COMMENT '企业ID',
  `data_source_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源名称',
  `data_source_type` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源类型',
  `data_source_database_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源的数据库名称',
  `data_source_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源的IP地址',
  `data_source_port` int(5) NULL DEFAULT NULL COMMENT '数据源的端口号',
  `data_source_username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源的账户名称',
  `data_source_password` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源的账户密码',
  `create_id` bigint(20) NULL DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_id` bigint(20) NULL DEFAULT NULL COMMENT '更新者ID',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint(4) NULL DEFAULT NULL COMMENT '删除标识（-1：不存在；1：存在）',
  PRIMARY KEY (`data_source_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 14 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of data_source
-- ----------------------------
INSERT INTO `data_source` VALUES (9, 1, 'data-view-template', 'MySQL', 'data-view-template', '127.0.0.1', 3306, 'root', 'root', 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);

-- ----------------------------
-- Table structure for image
-- ----------------------------
DROP TABLE IF EXISTS `image`;
CREATE TABLE `image`  (
  `image_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `image_name` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '图片名称',
  `image_path` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '图片位置',
  `image_size` bigint(20) NULL DEFAULT NULL COMMENT '图片大小',
  `business_id` bigint(20) NULL DEFAULT NULL COMMENT '企业ID',
  `create_id` bigint(20) NULL DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_id` bigint(20) NULL DEFAULT NULL COMMENT '更新者ID',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint(4) NULL DEFAULT NULL COMMENT '删除标识（-1：不存在；1：存在）',
  PRIMARY KEY (`image_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 14 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of image
-- ----------------------------
INSERT INTO `image` VALUES (9, '云资源监控-背景.png', '/group1/default/20210513/17/59/6/云资源监控-背景.png', 61983, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);
INSERT INTO `image` VALUES (10, '企业实时销售数据-背景.png', '/group1/default/20210513/18/00/6/企业实时销售数据-背景.png', 758743, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);
INSERT INTO `image` VALUES (11, '通用模板1-背景.png', '/group1/default/20210513/18/01/6/通用模板1-背景.png', 27247, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);
INSERT INTO `image` VALUES (12, '云服务监控-背景.png', '/group1/default/20210513/18/03/6/云服务监控-背景.png', 44365, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);
INSERT INTO `image` VALUES (13, '零售行业数据可视化-背景.png', '/group1/default/20210513/18/01/6/零售行业数据可视化-背景.png', 545340, 1, 1, '2021-05-19 10:12:18', 1, '2021-05-19 10:12:18', 1);

-- ----------------------------
-- Table structure for view_chart_item
-- ----------------------------
DROP TABLE IF EXISTS `view_chart_item`;
CREATE TABLE `view_chart_item`  (
  `item_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `instance_id` bigint(20) NULL DEFAULT NULL,
  `item_chart_data` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `item_chart_type` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item_choose` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item_data` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `item_height` bigint(20) NULL DEFAULT NULL,
  `item_i` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item_interval` bigint(20) NULL DEFAULT NULL,
  `item_option` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `item_refresh` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item_width` bigint(20) NULL DEFAULT NULL,
  `item_x` bigint(20) NULL DEFAULT NULL,
  `item_y` bigint(20) NULL DEFAULT NULL,
  `item_version` bigint(20) NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2185 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of view_chart_item
-- ----------------------------
INSERT INTO `view_chart_item` VALUES (2145, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 35, 'chart0', 8000, '{\"title\":\" 大数据计算服务运维视屏——测试项目\",\"fontColor\":\"#ffffff\",\"fontSize\":28,\"height\":35,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 500, 215, 15, 1);
INSERT INTO `view_chart_item` VALUES (2146, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart1', 8000, '{\"title\":\"服务器整体监测\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 180, 60, 100, 1);
INSERT INTO `view_chart_item` VALUES (2147, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart2', 8000, '{\"title\":\"MaxCompute任务总数\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 250, 60, 305, 1);
INSERT INTO `view_chart_item` VALUES (2148, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart3', 8000, '{\"title\":\"任务情况\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 125, 895, 305, 1);
INSERT INTO `view_chart_item` VALUES (2149, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart4', 8000, '{\"title\":\"表平均容量\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 130, 1545, 305, 1);
INSERT INTO `view_chart_item` VALUES (2150, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart5', 8000, '{\"title\":\"表储存容量\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 135, 60, 715, 1);
INSERT INTO `view_chart_item` VALUES (2151, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart6', 8000, '{\"title\":\"运行耗时最长任务\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 200, 495, 715, 1);
INSERT INTO `view_chart_item` VALUES (2152, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 50, 'chart7', 8000, '{\"title\":\"资源耗时最大任务\",\"fontColor\":\"#ffffff\",\"fontSize\":24,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 200, 895, 715, 1);
INSERT INTO `view_chart_item` VALUES (2153, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 20, 'chart8', 8000, '{\"title\":\"计算资源消耗\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 115, 75, 160, 1);
INSERT INTO `view_chart_item` VALUES (2154, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 20, 'chart9', 8000, '{\"title\":\"磁盘总空间/利用率\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 160, 530, 160, 1);
INSERT INTO `view_chart_item` VALUES (2155, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 20, 'chart10', 8000, '{\"title\":\"内存总数/利用率\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 140, 985, 160, 1);
INSERT INTO `view_chart_item` VALUES (2156, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 20, 'chart11', 8000, '{\"title\":\"在线结点数/结点率\",\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"height\":20,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 155, 1440, 160, 1);
INSERT INTO `view_chart_item` VALUES (2157, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"select sum(data) as data from template_1_crc_sum\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 50, 'chart12', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"GB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 135, 75, 205, 1);
INSERT INTO `view_chart_item` VALUES (2158, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_crc_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'false', '[]', 100, 'chart13', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"30\",\"30\"],[\"02/01\",\"160\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"90\",\"120\"],[\"05/01\",\"20\",\"70\"],[\"06/01\",\"190\",\"100\"],[\"07/01\",\"100\",\"70\"],[\"08/01\",\"150\",\"90\"],[\"09/01\",\"90\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 225, 230, 160, 1);
INSERT INTO `view_chart_item` VALUES (2159, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tds_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 50, 'chart14', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"TB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 90, 530, 205, 1);
INSERT INTO `view_chart_item` VALUES (2160, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart15', 8000, '{\"title\":\"/\",\"fontColor\":\"#ffffff\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}', 'false', 30, 600, 218, 1);
INSERT INTO `view_chart_item` VALUES (2161, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tds_sum WHERE type = \'ratio\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 35, 'chart16', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":32,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 80, 635, 214, 1);
INSERT INTO `view_chart_item` VALUES (2162, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tds_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'false', '[]', 100, 'chart17', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"90\",\"30\"],[\"02/01\",\"30\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"20\",\"180\"],[\"05/01\",\"50\",\"70\"],[\"06/01\",\"190\",\"120\"],[\"07/01\",\"170\",\"70\"],[\"08/01\",\"150\",\"90\"],[\"09/01\",\"40\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 225, 715, 160, 1);
INSERT INTO `view_chart_item` VALUES (2163, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tm_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 50, 'chart18', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"TB\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 90, 985, 205, 1);
INSERT INTO `view_chart_item` VALUES (2164, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart19', 8000, '{\"title\":\"/\",\"fontColor\":\"#ffffff\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}', 'false', 30, 1060, 218, 1);
INSERT INTO `view_chart_item` VALUES (2165, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tm_sum WHERE type = \'ratio\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 35, 'chart20', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":32,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 80, 1095, 214, 1);
INSERT INTO `view_chart_item` VALUES (2166, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tm_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'false', '[]', 100, 'chart21', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"16\",\"30\"],[\"02/01\",\"18\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"40\",\"120\"],[\"05/01\",\"20\",\"70\"],[\"06/01\",\"200\",\"100\"],[\"07/01\",\"90\",\"70\"],[\"08/01\",\"20\",\"90\"],[\"09/01\",\"90\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 225, 1165, 160, 1);
INSERT INTO `view_chart_item` VALUES (2167, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_onn_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 50, 'chart22', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"个\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 100, 1440, 205, 1);
INSERT INTO `view_chart_item` VALUES (2168, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart23', 8000, '{\"title\":\"/\",\"fontColor\":\"#ffffff\",\"fontSize\":22,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"center\"}', 'false', 30, 1535, 218, 1);
INSERT INTO `view_chart_item` VALUES (2169, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_onn_sum WHERE type = \'ratio\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 35, 'chart24', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":32,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 80, 1570, 214, 1);
INSERT INTO `view_chart_item` VALUES (2170, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_onn_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'false', '[]', 100, 'chart25', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"20%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"30\",\"30\"],[\"02/01\",\"160\",\"80\"],[\"03/01\",\"80\",\"20\"],[\"04/01\",\"90\",\"120\"],[\"05/01\",\"20\",\"70\"],[\"06/01\",\"190\",\"100\"],[\"07/01\",\"100\",\"70\"],[\"08/01\",\"150\",\"90\"],[\"09/01\",\"90\",\"30\"],[\"10/01\",\"60\",\"50\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 225, 1635, 160, 1);
INSERT INTO `view_chart_item` VALUES (2171, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_mcj_sum WHERE type = \'sum\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 30, 'chart26', 8000, '{\"fontColor\":\"#b3b3b3\",\"fontSize\":22,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 110, 100, 360, 1);
INSERT INTO `view_chart_item` VALUES (2172, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart27', 8000, '{\"title\":\"同比\",\"fontColor\":\"#b3b3b3\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 60, 550, 360, 1);
INSERT INTO `view_chart_item` VALUES (2173, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_mcj_sum WHERE type = \'year_on_tear\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 25, 'chart28', 8000, '{\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 60, 610, 365, 1);
INSERT INTO `view_chart_item` VALUES (2174, 85, '{\"dataSourceType\":\"\",\"database\":\"\",\"fileName\":\"\",\"sql\":\"\",\"x\":\"\",\"name\":\"\"}', 'TitleText', 'false', '[]', 30, 'chart29', 8000, '{\"title\":\"同比\",\"fontColor\":\"#b3b3b3\",\"fontSize\":20,\"height\":30,\"fontWeight\":\"normal\",\"textAlign\":\"left\"}', 'false', 60, 680, 360, 1);
INSERT INTO `view_chart_item` VALUES (2175, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_mcj_sum WHERE type = \'chain_ratio\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 25, 'chart30', 8000, '{\"fontColor\":\"#b3b3b3\",\"fontSize\":18,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":false,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"%\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 60, 740, 365, 1);
INSERT INTO `view_chart_item` VALUES (2176, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"legend\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_mcj_line\",\"chartType\":\"LineNormal\"}', 'LineNormal', 'false', '[]', 275, 'chart31', 8000, '{\"title\":{\"show\":false,\"text\":\"标准折线图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"}},\"legend\":{\"show\":false},\"grid\":{\"left\":\"5%\",\"top\":\"10\",\"right\":\"10\",\"bottom\":\"10\"},\"xAxis\":{\"show\":false,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":false,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":true},\"series\":[{\"type\":\"line\",\"lineStyle\":{},\"smooth\":true,\"showSymbol\":false},{\"type\":\"line\",\"lineStyle\":{\"type\":\"dashed\"},\"smooth\":true,\"showSymbol\":false}],\"dataset\":{\"source\":[[\"dimension\",\"1\",\"2\"],[\"01/01\",\"60\",\"70\"],[\"02/01\",\"50\",\"80\"],[\"03/01\",\"60\",\"80\"],[\"04/01\",\"60\",\"150\"],[\"05/01\",\"100\",\"90\"],[\"06/01\",\"70\",\"130\"],[\"07/01\",\"150\",\"50\"],[\"08/01\",\"70\",\"20\"],[\"09/01\",\"20\",\"90\"],[\"10/01\",\"55\",\"130\"],[\"11/01\",\"220\",\"40\"],[\"12/01\",\"100\",\"80\"]]},\"color\":[\"#E38092\",\"#FF64F4\"]}', 'false', 775, 45, 405, 1);
INSERT INTO `view_chart_item` VALUES (2177, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select name,value from template_1_jt_pie\",\"chartType\":\"PieNormal\"}', 'PieNormal', 'false', '[]', 250, 'chart32', 8000, '{\"title\":{\"text\":\"任务类型分布\",\"x\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"},\"show\":true,\"left\":\"center\",\"top\":\"bottom\"},\"legend\":{\"show\":false},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"40%\"],\"radius\":[\"50%\",\"70%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"TYPE_1\",\"32\"],[\"TYPE_2\",\"54\"],[\"TYPE_3\",\"45\"],[\"TYPE_4\",\"12\"],[\"TYPE_5\",\"40\"]]},\"color\":[\"#E99B9F\",\"#EE8287\",\"#BE69AC\",\"#9E5DB7\",\"#973CE4\"]}', 'false', 250, 900, 380, 1);
INSERT INTO `view_chart_item` VALUES (2178, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"name\":\"name\",\"value\":\"value\",\"sql\":\"select name,value from template_1_js_pie\",\"chartType\":\"PieNormal\"}', 'PieNormal', 'false', '[]', 250, 'chart33', 8000, '{\"title\":{\"text\":\"成功任务比例\",\"x\":\"center\",\"textStyle\":{\"color\":\"#ffffff\"},\"show\":true,\"left\":\"center\",\"top\":\"bottom\"},\"legend\":{\"show\":false},\"tooltip\":{\"trigger\":\"item\",\"formatter\":\"{a}<br/>{b}:{c}({d}%)\"},\"series\":[{\"type\":\"pie\",\"center\":[\"50%\",\"40%\"],\"radius\":[\"50%\",\"70%\"],\"roseType\":false,\"label\":{\"show\":false},\"labelLine\":{}}],\"dataset\":{\"source\":[[\"dimension\",\"\"],[\"TYPE_1\",\"82\"],[\"TYPE_2\",\"18\"]]},\"color\":[\"#EE8287\",\"#9E5DB7\",\"#973CE4\"]}', 'false', 250, 1210, 380, 1);
INSERT INTO `view_chart_item` VALUES (2179, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tac_sum WHERE type = \'sum1\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 50, 'chart34', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"GB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 160, 1550, 360, 1);
INSERT INTO `view_chart_item` VALUES (2180, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"value\":\"data\",\"sql\":\"SELECT * FROM template_1_tac_sum WHERE type = \'sum2\'\",\"chartType\":\"Counter\"}', 'Counter', 'false', '[]', 50, 'chart35', 8000, '{\"fontColor\":\"#ffffff\",\"fontSize\":40,\"fontWeight\":\"normal\",\"textAlign\":\"left\",\"thousandth\":true,\"prefix\":{\"title\":\"\",\"fontColor\":\"#ffffff\",\"fontSize\":16,\"fontWeight\":\"normal\"},\"unit\":{\"title\":\"GB\",\"fontColor\":\"#b3b3b3\",\"fontSize\":16,\"fontWeight\":\"normal\"}}', 'false', 120, 1750, 360, 1);
INSERT INTO `view_chart_item` VALUES (2181, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tac_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', '[]', 250, 'chart36', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10\",\"top\":\"\",\"right\":\"10\",\"bottom\":\"10%\"},\"xAxis\":{\"show\":true,\"type\":\"category\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":true,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":false},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"color\":{\"x\":0,\"y\":0,\"x2\":0,\"y2\":1,\"type\":\"linear\",\"global\":false,\"colorStops\":[{\"offset\":0,\"color\":\"#E38A99\"},{\"offset\":1,\"color\":\"#9E5DB7\"}]}},\"barWidth\":0}],\"dataset\":{\"source\":[[\"dimension\"],[\"2月\",\"235\"],[\"3月\",\"156\"],[\"4月\",\"123\"],[\"5月\",\"423\"],[\"6月\",\"456\"],[\"7月\",\"356\"],[\"8月\",\"456\"],[\"9月\",\"853\"],[\"10月\",\"456\"],[\"11月\",\"456\"],[\"12月\",\"456\"]]}}', 'false', 350, 1530, 425, 1);
INSERT INTO `view_chart_item` VALUES (2182, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"dimension\":\"无\",\"name\":\"x\",\"value\":\"y\",\"sql\":\"select * from template_1_tsc_histogram\",\"chartType\":\"HistogramNormal\"}', 'HistogramNormal', 'false', '[]', 280, 'chart37', 8000, '{\"title\":{\"text\":\"标准柱状图\",\"left\":\"center\",\"textStyle\":{\"color\":\"#fff\"},\"show\":false},\"legend\":{\"show\":false},\"grid\":{\"left\":\"10%\",\"top\":\"10\",\"right\":\"10\",\"bottom\":\"10\"},\"xAxis\":{\"show\":false,\"type\":\"value\",\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}}},\"yAxis\":{\"axisLine\":{\"show\":false,\"lineStyle\":{\"color\":\"#ffffff\"}},\"axisLabel\":{\"show\":true,\"color\":\"#ffffff\"},\"axisTick\":{\"show\":false},\"splitLine\":{\"show\":false,\"lineStyle\":{\"color\":[\"#cccccc\"]}},\"show\":true,\"type\":\"category\"},\"series\":[{\"type\":\"bar\",\"itemStyle\":{\"color\":{\"x\":1,\"y\":0,\"x2\":0,\"y2\":0,\"type\":\"linear\",\"global\":false,\"colorStops\":[{\"offset\":0,\"color\":\"#E38A99\"},{\"offset\":1,\"color\":\"#9E5DB7\"}]}},\"barWidth\":\"50%\"}],\"dataset\":{\"source\":[[\"dimension\"],[\"上海\",\"23\"],[\"深证\",\"13\"],[\"合肥\",\"2\"],[\"成都\",\"9\"],[\"安徽\",\"5\"],[\"北京\",\"10\"],[\"杭州\",\"14\"],[\"长沙\",\"24\"]]}}', 'false', 385, 40, 775, 1);
INSERT INTO `view_chart_item` VALUES (2183, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"sql\":\"select area,pv,series1,attribute from template_1_rlt_list\",\"chartType\":\"CarouselList\"}', 'CarouselList', 'false', '[]', 300, 'chart38', 8000, '{\"header\":{\"show\":false,\"height\":35,\"fontColor\":\"#ffffff\",\"fontSize\":13,\"data\":[{\"width\":\"100px\",\"label\":\"area\"},{\"width\":\"100px\",\"label\":\"pv\"},{\"width\":\"100px\",\"label\":\"series1\"},{\"width\":\"80px\",\"label\":\"attribute\"}]},\"body\":{\"height\":35,\"fontColor\":\"#e2e2e2\",\"fontSize\":14,\"speed\":3,\"rowNum\":8,\"data\":[[\"北京\",\"6715\",\"99.7%\",\"6696\"],[\"天津\",\"6715\",\"99.7%\",\"6696\"],[\"河北\",\"6715\",\"99.7%\",\"6696\"],[\"山西\",\"6715\",\"99.7%\",\"6696\"],[\"内蒙古\",\"6715\",\"99.7%\",\"6696\"],[\"辽宁\",\"6715\",\"99.7%\",\"6696\"],[\"大连\",\"6715\",\"99.7%\",\"6696\"],[\"吉林\",\"6715\",\"99.7%\",\"6696\"],[\"贵州\",\"6715\",\"99.7%\",\"6696\"],[\"黑龙江\",\"6715\",\"99.7%\",\"6696\"],[\"浙江\",\"6715\",\"99.7%\",\"6696\"],[\"江苏\",\"6715\",\"99.7%\",\"6696\"],[\"海南\",\"6715\",\"99.7%\",\"6696\"],[\"广东\",\"6715\",\"99.7%\",\"6696\"],[\"广西\",\"6715\",\"99.7%\",\"6696\"],[\"安徽\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"西藏\",\"6715\",\"99.7%\",\"6696\"],[\"宁夏\",\"6715\",\"99.7%\",\"6696\"],[\"湖南\",\"6715\",\"99.7%\",\"6696\"],[\"湖北\",\"6715\",\"99.7%\",\"6696\"],[\"山东\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"青海\",\"6715\",\"99.7%\",\"6696\"]]}}', 'false', 390, 455, 775, 1);
INSERT INTO `view_chart_item` VALUES (2184, 85, '{\"dataSourceType\":\"DataBase\",\"database\":9,\"sql\":\"select area,pv,series1,attribute from template_1_rlt_list\",\"chartType\":\"CarouselList\"}', 'CarouselList', 'false', '[]', 300, 'chart39', 8000, '{\"header\":{\"show\":false,\"height\":35,\"fontColor\":\"#ffffff\",\"fontSize\":13,\"data\":[{\"width\":\"250px\",\"label\":\"area\"},{\"width\":\"250px\",\"label\":\"pv\"},{\"width\":\"250px\",\"label\":\"series1\"},{\"width\":\"200px\",\"label\":\"attribute\"}]},\"body\":{\"height\":30,\"fontColor\":\"#e2e2e2\",\"fontSize\":12,\"speed\":3,\"rowNum\":10,\"data\":[[\"北京\",\"6715\",\"99.7%\",\"6696\"],[\"天津\",\"6715\",\"99.7%\",\"6696\"],[\"河北\",\"6715\",\"99.7%\",\"6696\"],[\"山西\",\"6715\",\"99.7%\",\"6696\"],[\"内蒙古\",\"6715\",\"99.7%\",\"6696\"],[\"辽宁\",\"6715\",\"99.7%\",\"6696\"],[\"大连\",\"6715\",\"99.7%\",\"6696\"],[\"吉林\",\"6715\",\"99.7%\",\"6696\"],[\"贵州\",\"6715\",\"99.7%\",\"6696\"],[\"黑龙江\",\"6715\",\"99.7%\",\"6696\"],[\"浙江\",\"6715\",\"99.7%\",\"6696\"],[\"江苏\",\"6715\",\"99.7%\",\"6696\"],[\"海南\",\"6715\",\"99.7%\",\"6696\"],[\"广东\",\"6715\",\"99.7%\",\"6696\"],[\"广西\",\"6715\",\"99.7%\",\"6696\"],[\"安徽\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"西藏\",\"6715\",\"99.7%\",\"6696\"],[\"宁夏\",\"6715\",\"99.7%\",\"6696\"],[\"湖南\",\"6715\",\"99.7%\",\"6696\"],[\"湖北\",\"6715\",\"99.7%\",\"6696\"],[\"山东\",\"6715\",\"99.7%\",\"6696\"],[\"新疆\",\"6715\",\"99.7%\",\"6696\"],[\"青海\",\"6715\",\"99.7%\",\"6696\"]]}}', 'false', 980, 880, 760, 1);

-- ----------------------------
-- Table structure for view_instance
-- ----------------------------
DROP TABLE IF EXISTS `view_instance`;
CREATE TABLE `view_instance`  (
  `instance_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '实例ID',
  `business_id` bigint(20) NULL DEFAULT NULL COMMENT '企业ID',
  `instance_background_color` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '背景颜色',
  `instance_background_img` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '背景图',
  `instance_width` bigint(20) NULL DEFAULT NULL COMMENT '宽',
  `instance_height` bigint(20) NULL DEFAULT NULL COMMENT '高',
  `instance_title` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '标题',
  `instance_view_thumbnail` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '缩略图',
  `instance_version` bigint(20) NULL DEFAULT NULL COMMENT '版本号',
  `create_id` bigint(20) NULL DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_id` bigint(20) NULL DEFAULT NULL COMMENT '更新者ID',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint(4) NULL DEFAULT NULL COMMENT '删除标识（-1：不存在；1：存在）',
  PRIMARY KEY (`instance_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 86 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of view_instance
-- ----------------------------
INSERT INTO `view_instance` VALUES (85, 1, '#263546', '/group1/default/20210513/17/59/6/云资源监控-背景.png', 1920, 1080, '', '', 1, 1, '2021-05-26 13:30:26', 1, '2021-05-26 17:36:42', 1);

SET FOREIGN_KEY_CHECKS = 1;
